### ISSUE TITLE
create develop branch

### ISSUE THREAD

**Issue by emj365** [xinfab/xinfab.github.io#1]
I just created new front-end demo. https://github.com/emj365/xinfab/tree/develop

Demo page: http://xinfab.emj365.com

That is not ready for publishing. Let's work on develop branch for new version website.

And I'll create pull request once it ready.

**Comment by lpgn** [comment]
done! Welcome onboard!

**Comment by emj365** [comment]
As we talked. We will do modify on develop for current version.
Counld you create a branch call `v2` as an empty branch?

**Comment by emj365** [comment]
Now I have admin right. Let me do this.

**Comment by emj365** [comment]
done, there is https://github.com/xinfab/Website/tree/v2
and I pushed my codes.

**Comment by lpgn** [comment]
cool
