### ISSUE TITLE
fork the repos and create your pull request

### ISSUE THREAD

**Issue by emj365** [xinfab/xinfab.github.io#5]
If you need to maintain the content of the website. Please take look this.

Suggestion:

It's better to fork the repos to your account if you want to contribute.
After that, you can modify in your develop branch.
When you want to submit your contribution, create the pull request.
- [ ] use Github fork the main repository
- [ ] commit on your branch
- [ ] Push your changes to your repository
- [ ] create pull request to the main repository

You could try, any question you could comment here.

**Comment by emj365** [comment]
Be careful push to the main repository directly is a bad idea.

**Comment by emj365** [comment]
@evawxiao @Dannykuo
Any suggestion?

**Comment by lpgn** [comment]
@emj365 we need a Github workshop to make sure all contributors know the basics.

Would you want to teach one?

**Comment by emj365** [comment]
I'd like to teach. Let's plan the work shop.

But fork first and play GUI GitHub client by self will be great. Just make sure push to your own fork only.

None admin can't push to repository directly in the organization. (No permission)

**Comment by emj365** [comment]
Even you don't have git client installed you could modify files on the GitHub(in your fork). It works fine like fix few typo mistake.

**Comment by emj365** [comment]
Forget it. Let's make it more simple.

**Comment by lpgn** [comment]
agreed not all contributors will know how to use git
