### ISSUE TITLE
Fab-manager

### ISSUE THREAD

**Issue by lpgn** [xinfab/xinfab.github.io#6]
@emj365 we should study https://github.com/xinfab/fab-manager as it is really what we need.

**Comment by emj365** [comment]
This issue is not about XinFab website. We should find a better place to put it.

Do it later.

**Comment by emj365** [comment]
Maybe open the issues feature in https://github.com/xinfab/fab-manager.

**Comment by lpgn** [comment]
got it

**Comment by emj365** [comment]
we have https://github.com/xinfab/fab-world now.
