### ISSUE TITLE
set domain for v2 demo

### ISSUE THREAD

**Issue by emj365** [xinfab/xinfab.github.io#7]
We can use the GitHub Pages as the web server for the demo like I publish on http://xinfab.emj365.com.

We will do:
- [x] figure out a sub-domain name like staging.xinlab.com @evawxiao @lpgn 
- [x] Modify CNAME file @emj365
- [x] Configuring a custom subdomain with your DNS provider point to xinfab.github.io @lpgn 

Reference: https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/

**Comment by emj365** [comment]
BTW: Now, `gh-pages` branch is the content of http://xinfab.github.io/Website/.
But it only works with address like http://staging.xinfab.com.

So, let's do it with issue.

**Comment by lpgn** [comment]
finished my tasks check beta.xinfab.com points to xinfab.github.io

**Comment by lpgn** [comment]
done cname as well

**Comment by lpgn** [comment]
can we close this one?

**Comment by lpgn** [comment]
@emj365 v2 subdomain doen't work probabily github can host only one page at time?

**Comment by emj365** [comment]
@lpgn 

I didn't finish my part. When I finish this, I will notice here.
There is one Github Page for one Github Repository(used to the project page).

It's better to configure the auto deploy(when master merged) to the VPS in future.

**Comment by emj365** [comment]
It's working. http://beta.xinfab.com/

**Comment by emj365** [comment]
> @emj365 v2 subdomain doen't work probabily github can host only one page at time?

BTW: You could create more public repositories for more Github Pages. The only problem is Github vs GFW.
